server:
  port: 8024
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: gmlehd0201@gmail.com
    password: fzjiczesxgiqtqur
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:log4jdbc:mysql://database-1.cmnw7bfcaeuu.ap-northeast-2.rds.amazonaws.com:3306/insta?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: heedong
    password: #yhd15750201
mybatis:
  type-aliases-package: com.sbs.untact.dto
custom:
  genFileDirPath: C:/work/untact-usr-sb-file
  siteMainUri: http://3.37.59.223:8024/
  siteName: 인스타
  emailFrom: no-reply@localhost
  emailFromName: 인스타알림봇
  needToChangePasswordFreeDays: 90
  logging:
    dir: log
    level: debug